name: Java Tests

on: [push, pull_request]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Run build with Gradle Wrapper
      working-directory: ./roguelike-game
      run: ./gradlew build
